name: go tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY_IMAGE: helmunittest/helm-unittest
  GO_VERSION: 1.22.x
      
jobs:
  full-test:
    name: full sdk and tools test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # tests for target OS
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - name: checkout
      # https://github.com/actions/checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: setup go
      # https://github.com/actions/setup-go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: ${{ env.GO_VERSION }}

    # Make results directory
    - name: Install JUnit plugin for uploading testresults
      run: |
        mkdir -p test-results

    # Install using go install
    - name: Install JUnit plugin for uploading testresults
      run: |
        go install github.com/jstemmer/go-junit-report/v2@latest

    # Run tests with nice formatting. Save the coverage and junit test results in test-results
    - name: Run tests
      run: |
        go test ./... -coverprofile=test-results/coverage -v -covermode=atomic 2>&1 | go-junit-report -set-exit-code > test-results/go-test-report.xml

    - name: SonarCloud Scan
      # https://github.com/sonarsource/sonarcloud-github-action
      uses: sonarsource/sonarcloud-github-action@e44258b109568baa0df60ed515909fc6c72cba92 # v2.3.0
      if: matrix.os == 'ubuntu-latest' && env.SONAR_TOKEN != ''
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    # Upload the original go test log as an artifact for later review.
    - name: Upload test log
      # https://github.com/EnricoMi/publish-unit-test-result-action
      uses: EnricoMi/publish-unit-test-result-action@567cc7f8dcea3eba5da355f6ebc95663310d8a07 # v2.17.0
      if: always() && matrix.os == 'ubuntu-latest'
      with:
        files: |
          test-results/go-test-report.xml

  validate_docker:
    name: build and test docker
    runs-on: ubuntu-latest
    needs:
      - full-test
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - name: checkout
      # https://github.com/actions/checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        fetch-depth: 1

    - name: setup go
      # https://github.com/actions/setup-go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: ${{ env.GO_VERSION }}

    # Run docker-tests
    - name: Build docker-test
      run: |
        make test-docker

    - name: Retrieve versions
      run: |
        helmPluginVersion=$(sed -n -e 's/version:[ "]*\([^"]*\).*/\1/p' plugin.yaml)
        echo "HELM_PLUGIN_VERSION=${helmPluginVersion}" >> $GITHUB_ENV

    # Run trivy security
    - name: Run Trivy vulnerability scanner
      # https://github.com/aquasecurity/trivy-action
      uses: aquasecurity/trivy-action@6e7b7d1fd3e4fef0c5fa8cce1229c54b2c9bd0d8 # 0.24.0
      with:        
        image-ref: ${{ env.REGISTRY_IMAGE }}:${{ env.HELM_PLUGIN_VERSION }}
        format: sarif
        output: trivy-results.sarif
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@429e1977040da7a23b6822b13c129cd1ba93dbb2 # v3.26.2
      if: always()
      with:
        sarif_file: trivy-results.sarif
        